### ISSUE TITLE
Real Concurrency

### ISSUE THREAD

**Issue by TrevorBasinger** [fantasyland/fantasy-promises#13]
What do people think about baking in Webworkers and nodejs threads?

If I understand correctly, the current implementation doesn't give all the benefits of what a Future/Promise is supposed to.

I'd be happy to start putting together a PR for this. But first, is there a limitation that exists that I am not aware of?

**Comment by TrevorBasinger** [comment]
And once again I understand the limitations of my toolset.

**Comment by puffnfresh** [comment]
@TrevorBasinger what's the limitation?

**Comment by TrevorBasinger** [comment]
@puffnfresh -- Well, node runs on a single thread. It doesn't use OS threads offered by the kernel. Theoretically, I guess you could spawn child processes, but I didn't really think too deeply about it. I figured, if it could be done, someone else would have done it before me or would have raised the issue before now. I'm still interested in hearing someone else's thoughts.

**Comment by puffnfresh** [comment]
@TrevorBasinger you could definitely write a V8 [node.js addon](http://nodejs.org/api/addons.html) to support web workers.
