### ISSUE TITLE
some clarifications

### ISSUE THREAD

**Issue by paulmillr** [fantasyland/fantasy-promises#4]
it’s not very clear how exactly to use fantasy promises for folks with currently standard node bg (e.g. me).

any points on how this code can be rewritten?

``` coffeescript
compile = (realPath, callback) ->
  fs.readFile realPath, 'utf-8', (error, fileContent) ->
    return callback 'Reading' + error if error?
    lint fileContent, path, (error) ->
      return callback 'Linting' + error if error?
      compile fileContent, path, (error, result) ->
        return callback 'Compiling' + error if error?
        getDependencies fileContent, path, (error, dependencies) ->
          return callback 'Dependency parsing' + error if error?
          callback null, {data: result, compilationTime: Date.now(), dependencies}
```

**Comment by TrevorBasinger** [comment]
Hey @paulmillr,
I can offer some help if you still haven't figured this out.

```
var compile = function (path) {
    return new Promise (function (resolve) {
        doAsyncOperation (opts, function (err, result) {
            return resolve (result);
        });
    });
}

compile.fork (callback);
```

This is a very basic way to use a Promise. However, the real power comes into play when you start using some of the more functional idioms with them such as chaining (bind) or mapping.
A Promise is a monad, so by definition it inherits the mutations also available to the types it is derived from such as Applicative Functors and Monoids.

If this doesn't make sense, I suggest you take a little time to look at the [fantasyland specs](https://github.com/fantasyland/fantasy-land).

**Comment by stevemao** [comment]
It's still not clear how to `reject()` to me

**Comment by safareli** [comment]
I would recommend checking documentation/examples of https://github.com/fluture-js/Fluture/

**Comment by stevemao** [comment]
Thanks @safareli 
Looks like `Either` is the way to go.

**Comment by davidchambers** [comment]
This project is no longer maintained. See #16 for details.
